### ISSUE TITLE
tsx render里如何直接引用element-ui组件

### ISSUE THREAD

**Issue by dave-wind** [thundernet8/Vue-TS-Boilerplate#2]
### 想请教一下如何在tsx里直接引用 element-ui组件
> 比如我 引用 el-button 报错

```js
 <TestComponent msg={"msg from parent"}>
                <h1>Prop 传递值:{this.propMessage}</h1>
                <h2 onClick={this.testFuc}>{this.text}</h2>
                <a href="#/" class="router-link-active">Back to home</a>
                <el-button></el-button>
            </TestComponent>
```

#### 尝试的方法
 > 第一种
```
// in element-ui.d.ts

declare module "element-ui";
```
报错：Property 'el-button' does not exist on type 'JSX.IntrinsicElements'.

> 第二种 
```js
import {Button} from "element-ui"

 <TestComponent msg={"msg from parent"}>
                <h1>Prop 传递值:{this.propMessage}</h1>
                <h2 onClick={this.testFuc}>{this.text}</h2>
                <a href="#/" class="router-link-active">Back to home</a>
                <Button onClick={this.testFuc}></Button>
            </TestComponent>
```
报错：JSX element class does not support attributes because it does not have a '_props_' property.
Property 'onClick' does not exist on type '{}'.

不太懂tsx 里怎么引入第三方组件  thundernet8! 求赐教~

**Comment by thundernet8** [comment]
@dave-wind `onClick`是react的写法，vue里面用`@click`

**Comment by gooqiao** [comment]
第一种报错是因为没有全局注册element-ui组件，第二种是jsx配置问题，检查jsx.ElementAttributesProperty属性名，并在props声明中加入onClick属性，这是vue使用tsx做props验证的方案，ts目前对vue的props验证不太友好。详细说明可参考https://www.tslang.cn/docs/handbook/jsx.html
